### PR TITLE
Fix race condition, missing `animationend` event when `animationstart` callback is slow to call.

### LINKED ISSUE #35: Race-condition #2, Subscribing to `animationend` after `animationstart` can lead to missing the `animationend` event.
To reproduce:

1. Include an element with a `repeat.for` over an array.
2. Add opacity transition lasting 0.1 second to each repeated item.
3. Add 25 items to list.
4. Add another 25 items to list after 0.05 seconds.

With only 50 animated items on the screen at one time coupled with the short animation time the `animationend` event can fire before the callback that was supplied to the `animationstart` event fires. As this code doesn't register for the `animationend` event until the `animationstart` callback fires the consequence is the `animationend` event will never be detected and promise chains will go unresolved.

The solution is to subscribe to both events at the same time, you can test that the start event fired by setting a flag.

I have a fix in the works for this built on top of https://github.com/aurelia/animator-css/pull/33 so I suppose I'll submit it when that has been merged.

These two changes together make `repeat.for` + `animations` rock solid for me :)

### PR DESCRIPTION
**Pull request by ohjames**
fixes #35 built on top of the PR for https://github.com/aurelia/animator-css/pull/33

### CODE REVIEW

**Comment by zewa666** [comment]
first of all, big thank you @ohjames for your great work. I'm not really a fan of the introduced variable `verifyKeyframesExist` and the additional complexity, but the removal of the timeouts for sure does make the plugin overall better.

Code looks good but not all tests seem to pass. There are 3 staggering unit tests that fail. Could you verify that on your machine as well? Perhaps the issue is related to my crappy old macbook. Maybe just give it a try with a small staggering demo. If that works I'm fine with merging this.

Again great work and thank you for the contribution. Also sorry for catching my while being abroad.

**Comment by ohjames** [comment]
@zewa666 I'm not a fan of the verifyKeyframesExist work having to be done either, but the alternative is that if a user refers to an animation that doesn't exist... their animation promises will never get resolved. You could always document it well in the aurelia documentation though... that using non-existing keyframes will lead to catastrophy. You can disable the check with an option... so that people who know what they are doing can remove the keyframe check and accept responsibility.

The stagger tests work fine to me with both the `race-condition-fix` and `race-condition2-fix` branches. I assume you tested with `race-condition2-fix` since that's the PR you are commenting on, but if you were on the former branch then perhaps the latter could solve the issue.

Otherwise I'm not sure. This is chromium on mac os? I'm using chromium on Linux here and I've also tested with firefox. I've run these tests many times yet and they seem to reliably pass.

**Comment by ohjames** [comment]
```bash
james@minchil animator-css % gulp build && gulp test
[17:02:19] Using gulpfile ~/projects/animator-css/gulpfile.js
[17:02:19] Starting 'build'...
[17:02:19] Starting 'clean'...
[17:02:19] Finished 'clean' after 34 ms
[17:02:19] Starting 'build-index'...
[17:02:19] Finished 'build-index' after 34 ms
[17:02:19] Starting 'build-es6'...
[17:02:19] Starting 'build-commonjs'...
[17:02:19] Starting 'build-amd'...
[17:02:19] Starting 'build-system'...
[17:02:20] Finished 'build-commonjs' after 1.09 s
[17:02:20] Finished 'build-amd' after 1.09 s
[17:02:20] Finished 'build-system' after 1.08 s
[17:02:20] Finished 'build-es6' after 1.09 s
[17:02:20] Starting 'build-dts'...
[17:02:20] Finished 'build-dts' after 8.17 ms
[17:02:20] Finished 'build' after 1.17 s
[17:02:21] Using gulpfile ~/projects/animator-css/gulpfile.js
[17:02:21] Starting 'test'...
07 12 2015 17:02:22.609:WARN [watcher]: Pattern "/home/james/projects/animator-css/node_modules/karma-jasmine-jquery" does not match any file.
07 12 2015 17:02:23.784:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
07 12 2015 17:02:23.789:INFO [launcher]: Starting browser Chrome
07 12 2015 17:02:24.691:INFO [Chrome 46.0.2490 (Linux 0.0.0)]: Connected on socket uLT7Wd2wxYwO7UWsAAAA with id 60357629
Chrome 46.0.2490 (Linux 0.0.0): Executed 54 of 54 SUCCESS (20.055 secs / 20.03 secs)
[17:02:45] Finished 'test' after 24 s
```

**Comment by zewa666** [comment]
all right, yeah looking forward to try it out on my PC when at home. In the meantime @EisenbergEffect if you could give this PR a testdrive and it passes, I'd definitely like to see the changes released asap. It will certainly have a big impact on other issues as well and maybe solve them too. So lets see what happens.

**Comment by ohjames** [comment]
Could add a travis.yml/circle.yml to have the tests automatically run on a CI server? Some of them provide a running Xvfb instance so the graphical nature of the tests wouldn't be an issue.

**Comment by zewa666** [comment]
Ok I've tried it now on my PC and everything works fine :+1: 
Big thanks for your contribution @ohjames. let's get this released as soon as you can @EisenbergEffect

**Pull request merged**
