### PR TITLE
feat(animator-lifecycle)

### PR DESCRIPTION
**Pull request by joelcoxokc**
Resolves issue from #28 
Also Please see notes from #28

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@joelcoxokc I think you will need to rebase this on the latest version in master.

**Comment by EisenbergEffect** [comment]
@joelcoxokc Can you rebase this on master? We can't merge it as is.

**Comment by joelcoxokc** [comment]
@EisenbergEffect Yes I will

**Comment by ohjames** [comment]
Just to clear up something from the description of this issue, #28 is already solved in the most recent release. Glad the code is being cleaned up whether the fix is still needed or not.

**Comment by EisenbergEffect** [comment]
I'm going to close this for now. We've had some big changes and a couple more fixes have come in. We would like to rework the innards. It's probably better to do it as a new PR.

**Comment by ohjames** [comment]
@EisenbergEffect Might any of those changes fix the super serious repeat bug: https://github.com/aurelia/templating-resources/issues/183

I've had to stop demoing my project to people because the first thing they raise is how badly the lists become out of order :( Our team is worried we made the wrong choice with Aurelia :(

**Comment by joelcoxokc** [comment]
@Ohjames one of the greatest things about Aurelia, is that it's pluggable and extensible. The CSS animator is obviously not as extensive a something like GreenSock. I personally dont think the animator should determine whether you made the right decision on a framework. 

Let chat some time this coming weekend, and maybe we can nail down the bug.

**Comment by ohjames** [comment]
@joelcoxokc The issue isn't with the animator but to do with the way the framework interacts with the animator leading to a desync. I spent about 30 hours trying to fix the various desync issues in aurelia leading to three PRs that are now part of Aurelia... but this last desync issue really worries me. I think it might involve some really significant changes.

**Comment by joelcoxokc** [comment]
What exactly do you mean by desync, I think I have an idea...

Or do you have a reference where you recently discussed?

**Comment by martingust** [comment]
@joelcoxokc Here is the issue for the bug @ohjames referring to https://github.com/aurelia/templating-resources/issues/183

**Pull request closed without merging**
