### PR TITLE
keep it short :)

### PR DESCRIPTION
**Pull request by matjaz**

### CODE REVIEW

**Comment by zewa666** [comment]
@EisenbergEffect this ones ok lets merge it with the next release cycle

**Comment by EisenbergEffect** [comment]
@matjaz Would you mind signing our CLA please? https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1

**Comment by Aaike** [comment]
oh i thought i already signed that months ago :)

anyway , done !

**Comment by EisenbergEffect** [comment]
@Aaike You did. This PR was from @matjaz though.

**Comment by matjaz** [comment]
I already signed it. https://github.com/aurelia/dependency-injection/issues/15

**Pull request merged**
