### PR TITLE
fix(CssAnimator): clear event handlers when there's no animation

### LINKED ISSUE #47: Animator interfering with other CSS Transitions
Plunker Example:
http://plnkr.co/edit/ZTqND2?p=preview

Transitions applied to elements that do not have the au-animate attribute on them are affected by the animator in that the element is hidden immediately after the transition has completed. Bug only appears where "show.bind" condition is applied to the same element. The same issue doesnt seem to occur with if.bind.

Simple example above where a fadeIn affect ends with the element being hidden where show.bind is used.

Once the element is hidden, the transition effect no longer works if re-applied.

Bug also present in latest version of aurelia animator (1.0.0-beta.1.2.0).

Thanks

### PR DESCRIPTION
**Pull request by z-brooks**
Event handlers were not being removed in addClass & removeClass. This was causing problems when paired with the show attribute.

fixes #47

### CODE REVIEW

**Comment by zewa666** [comment]
hmm yeah that makes sense actually. Thanks for the contribution, have you already signed the CLA?

**Comment by z-brooks** [comment]
Np. Yes I've signed it.

**Comment by zewa666** [comment]
ok one more thing, can I ask you to add at least a simple unit test to verify that approach? After that I'll merge it right away

**Comment by z-brooks** [comment]
Ok I've added a test.

**Comment by zewa666** [comment]
awesome @z-brooks. Thanks for the contribution :+1:

**Pull request merged**
