### PR TITLE
fix(stagger): delay calculation

### LINKED ISSUE #55: Infinite scrolling animation delays accumulate
**I'm submitting a bug report**
- **Library Version:**
  1.0.1

**Please tell us about your environment:**
- **Operating System:**
  Linux (Debian Jessie)
- **Node Version:**
  4.5.0
  
  
- **NPM Version:**
  3.10.6
  
  
- **Build Tooling:**
  Using Aurelia CLI version 0.18.0
- **Browser:**
  Chrome 53
- **Language:**
  ESNext

**Steps:**
- Have a list with `au-stagger` with a 0.2s transition delay
- Add 1000 animated items
- Wait for animations to complete
- Add 1000 more animated items
- **What is the expected behavior?**
- First new animated item immediately begins animation
- **What is the actual behavior?**
- First new animated item waits for 1000 \* 0.2s before it begins animation
- **What is the motivation / use case for changing the behavior?**
- Infinite scrolling - otherwise there are longer and longer unnecessary delays as you scroll

### PR DESCRIPTION
**Pull request by z-brooks**
Stagger delay calculation for new elements included existing elements.

fixes #55

### CODE REVIEW

**Comment by zewa666** [comment]
This sounds great, I'll take a proper look tomorrow. Thx for the contribution

**Comment by zewa666** [comment]
@z-brooks ok so I've zoomed through it and fixed some linting issues. Great work, like the refactoring you did for enter/leave to reduce code duplication 👍

**Comment by 7Pass** [comment]
I'm sorry if this looks silly but I don't see `au-stagger-leave` being used anymore, is this intended? Unfortunately, I could not find any documentation to verify how I should use it, and I'm unable to use enter only staggering. Tests are passing, but they do not verify if there is a delay between items or not.

**Comment by zewa666** [comment]
@7Pass thanks to the help of @z-brooks this got fixed and merged. Release inbound :) Thanks for reporting and fixing guys

**Comment by 7Pass** [comment]
I look forward to the release. Thanks all for the great work.

**Pull request merged**
